version: '3'
services:
  php:
    build:
      context: . # Répertoire actuel (où se trouve votre Dockerfile PHP)
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jam