version: '3'
services:
  php:
    build:
      context: ./docker/php-fpm # Répertoire actuel (où se trouve votre Dockerfile PHP)
    volumes:
      - .:/srv/www:cached
      - ./vendor:/srv/www/vendor:cached
      - ./node_modules:/srv/www/node_modules:cached
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/www/public:cached
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jam