ARG PHP_VERSION=8.2
ARG NODE_MAJOR=20

FROM php:${PHP_VERSION}-fpm

COPY certs /usr/local/share/ca-certificates
COPY certs /usr/lib/ssl

RUN update-ca-certificates \
    && apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libicu-dev \
    && apt-get update && apt-get install -y openssl && apt-get install acl \
    && docker-php-ext-configure intl \
    && docker-php-ext-install zip \
    intl \
    && docker-php-ext-enable intl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg && \
    mkdir -p /etc/apt/keyrings &&\
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list | bash - && \
    apt-get update && \
    apt-get install nodejs -y \
    npm

RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /srv/www/

COPY conf.d/app.ini $PHP_INI_DIR/conf.d/app.ini

COPY ../.. .

EXPOSE 9000

CMD ["php-fpm"]